### PR TITLE
Refactor delivery message

### PR DESCRIPTION
**Pull request by mxgrey**

### CODE REVIEW

**Comment by tanyouliang95** [comment]
Nice that this. Is it better if we can have this 'item' msg in `rmf_workcell_msgs`?

**Comment by mxgrey** [comment]
If it's moved to `rmf_workcell_msgs` would it still be called `DispenserRequestItem`?

Related to that, are there any thoughts on moving everything from `rmf_dispenser_msgs` into `rmf_workcell_msgs`? I don't have strong feelings on this either way.

**Comment by aaronchongth** [comment]
I think we should go ahead and have this inside `rmf_dispenser_msgs`, I have started some migration work on another branch (https://github.com/osrf/rmf_core/tree/common-workcell-msg-scheme), with the intention to migrate `sharp-rmf/rmf-workcell` repo to use `rmf_workcell_msgs` instead of `rmf_msgs`.

The discussions for naming `DispenserRequestItem` would be more relevant then

**Comment by tanyouliang95** [comment]
Yeap, either way will do. Since migration is goin on, we can keep it this way for the time being. :+1:

**Comment by mxgrey** [comment]
I'll merge this soon if there are no objections.

**Pull request merged**
