### PR TITLE
Add blurb about traffic conflict management

### PR DESCRIPTION
**Pull request by mxgrey**
Due to recent inquiries about traffic conflict management, I've added a blurb about it to the FAQ page.

### CODE REVIEW

**Comment by Jason-Zhou1** [comment]
HI mxgrey,
I have found in the office_loop of rmf_demos that one robot A has higher priority over another robot B in the conflict resolution. When conflict arises, robot B either wait for the robot A to pass over or choose another route to go to void the conflict. Am I right? Is this negotiation issue solved in the Negotiation.hpp file or other files?
Thank you!

**Comment by mxgrey** [comment]
The Negotiation system is relatively new development. You'd have to check out the `develop` branch (instead of the default `master` branch) of `rmf_core` to see the behavior from the Negotiation system. There are a couple of [known issues](https://github.com/osrf/rmf_core/pull/92#pullrequestreview-391950457) on the `develop` branch that are being resolved right now, which is why it hasn't been merged to master. I expect to have most of those fixed and tested by early next week.

The implementation on the current `master` is a prototype from December. The way it works is when a traffic conflict occurs, the first traffic schedule participant that offers a way to accommodate the conflict will be the one whose accommodation is accepted. Since Robot A and Robot B belong to the same fleet adapter which operates on a single thread, Robot A will always be the first one to compute and transmit an accommodation to the schedule, so Robot A will always be moving out of the way of Robot B. This wasn't intentionally programmed; it's just a coincidental artifact of how the prototype was implemented and how the scenario was configured. The new negotiation system should produce more efficient and more sensible plans.

**Comment by Jason-Zhou1** [comment]
Hi mxgrey,
I have seen some of your slides about the negotiation procedure: [Here are the slides](https://docs.google.com/presentation/d/1zhN_4Wwt64q2Y4fRxK80p07H5AL0rTCt9w60k5b-9Fs/edit?usp=sharing)
The slides describe the negotiation concept and procedure very clearly and easy to understand. Do you have any slides about the conflict detection logic and procedure yet?

**Comment by mxgrey** [comment]
> Do you have any slides about the conflict detection logic and procedure yet?

No, I don't anticipate there will be time for a write-up on this for a long time, probably not for another year. The key idea is that it uses A* while taking time into account, and it performs continuous collision detection for each A* expansion to prune out infeasible branches.

I think the API of the [planner](https://github.com/osrf/rmf_core/blob/master/rmf_traffic/include/rmf_traffic/agv/Planner.hpp) should simple enough to use, though. Just give it a description of your robot, a snapshot of the current schedule, and the start and end conditions. Then it will plan out a conflict-free itinerary for you.

**Pull request merged**
