### PR TITLE
Feature/multiple deliveries

### PR DESCRIPTION
**Pull request by cnboonhan94**
This PR is targeted at full control `rmf_fleet_adapter`s, to 

1) implement concurrent deliveries by multiple robots
2) fix a possible bug in the [previous implementation](https://github.com/osrf/rmf_core/blob/master/rmf_fleet_adapter/src/full_control/FleetAdapterNode.cpp#L475) where the `_have_delivery_request` flag was not unset after completion of tasks, which prevented the processing of further delivery requests after the first.

### CODE REVIEW

**Comment by mxgrey** [comment]
I'll be completely honest: There was something horribly broken with receiving delivery requests, and I put in that terrible `_have_delivery_request` on purpose to deal with it at the last minute. I'm struggling to remember exactly what the issue was, but I vaguely remember that if multiple delivery requests were issued, then the fleet adapter would break in some awful confusing way (maybe a segfault?).

I decided to punt on it and leave it unsolved since we're working on a complete remake of the fleet adapters, but if there's an interest in getting this to work in the old fleet adapters that were made for DP2, then I would recommend testing this extensively in simulation.

**Comment by cnboonhan94** [comment]
it happens that multiple deliveries is necessary for a simulation world we are working on. so far my limited testing has not yielded any segfaults, but ill be sure to update this thread if i see any.
In the meantime, would it be convenient to leave a legacy branch for this temporary fix in the repo for now?

**Comment by mxgrey** [comment]
I don't mind merging it into master; I just wanted to make sure you guys don't get hurt by that absurd bug that I never managed to track down. If your testing has been turning out okay, then I'm happy to move forward with it.

In case I can't remember the bug correctly, you might also want to try the following tests:
* Spam the same delivery request (i.e. a delivery request with the same task ID) multiple times
* Send multiple delivery requests (i.e. delivery requests with different task IDs) before a delivery is finished
* Do the above with multiple robots in the environment

**Comment by cnboonhan94** [comment]
sure thing. will work on the simulation and carry out these testing as well, and report what I find. Thanks!

**Comment by cnboonhan94** [comment]
Hello there! Sorry for the late response. Ive been testing quite a bit with multiple deliveries, and have not seen any issues as you described. There has been * some * side effects which I'm not sure are directly related to multiple deliveries. nevertheless for many situations, especially conflict free situations, it has been quite ok for me.

**Comment by mxgrey** [comment]
Thanks for the contribution!

**Pull request merged**
