### PR TITLE
Use optional of reference wrapper

### PR DESCRIPTION
**Pull request by aaronchongth**
Signed-off-by: Aaron Chong <aaronchongth@gmail.com>

### CODE REVIEW

**Review by Yadunund — APPROVED** [review]
Thanks for addressing the UB. Pretty cool solution!

**Comment by mxgrey** [comment]
A more classic alternative would be to return a `Participant*` which has a `nullptr` value if the object isn't available. That said, there's nothing wrong with this approach; the only downside is the `std::optional` uses up one extra byte to track whether the object is available.

**Comment by aaronchongth** [comment]
I see, yeah that would be a good idea. I was trying to prevent any use of raw pointers in the API, thanks for the tip!

**Comment by mxgrey** [comment]
It's okay to use raw pointers in the API as long the raw pointer is telling the user "You are allowed to have access to view/mutate this object, but you do not own its memory allocation". You should absolutely not use raw pointers if the user is expected to own and manage the memory allocation of the object.

**Pull request merged**
